import { eCharacterClass } from "../enums/character-class.enum";

export const CLASS_CODE_MAP = {
	히어로: eCharacterClass.HERO,
	팔라딘: eCharacterClass.PALADIN,
	다크나이트: eCharacterClass.DARK_KNIGHT,
	소울마스터: eCharacterClass.SOUL_MASTER,
	미하일: eCharacterClass.MIHAEL,
	블래스터: eCharacterClass.BLASTER,
	"데몬 슬레이어": eCharacterClass.DAEMON_SLAYER,
	"데몬 어벤저": eCharacterClass.DAEMON_AVENGER,
	아란: eCharacterClass.ARAN,
	카이저: eCharacterClass.KAISER,
	아델: eCharacterClass.ADELE,
	제로: eCharacterClass.ZERO,
	"아크메이지(불,독)": eCharacterClass.ARCHMAGE_FP,
	"아크메이지(썬,콜)": eCharacterClass.ARCHMAGE_TC,
	비숍: eCharacterClass.BISHOP,
	플레임위자드: eCharacterClass.FLAME_WIZARD,
	배틀메이지: eCharacterClass.BATTLE_MAGE,
	에반: eCharacterClass.EVAN,
	루미너스: eCharacterClass.LUMINOUS,
	일리움: eCharacterClass.ILLIUM,
	라라: eCharacterClass.LARA,
	키네시스: eCharacterClass.KINESIS,
	보우마스터: eCharacterClass.BOW_MASTER,
	신궁: eCharacterClass.ARCHERY_MASTER,
	패스파인더: eCharacterClass.PATH_FINDER,
	윈드브레이커: eCharacterClass.WIND_BREAKER,
	와일드헌터: eCharacterClass.WILD_HUNTER,
	메르세데스: eCharacterClass.MERCEDES,
	카인: eCharacterClass.KAIN,
	나이트로드: eCharacterClass.NIGHT_LORD,
	섀도어: eCharacterClass.THIEF_MASTER,
	듀얼블레이더: eCharacterClass.DUAL_BLADE,
	나이트워커: eCharacterClass.NIGHT_WALKER,
	제논: eCharacterClass.XENON_PIRATE,
	팬텀: eCharacterClass.PANTOM,
	카데나: eCharacterClass.KADENA,
	칼리: eCharacterClass.KALI,
	호영: eCharacterClass.HOYOUNG,
	바이퍼: eCharacterClass.VIPER,
	캡틴: eCharacterClass.CAPTAIN,
	캐논슈터: eCharacterClass.CANON_SHOOTER,
	스트라이커: eCharacterClass.STRIKER,
	메카닉: eCharacterClass.MECHANIC,
	은월: eCharacterClass.EUNWAL,
	"엔젤릭 버스터": eCharacterClass.ANGELIC_BUSTER,
	아크: eCharacterClass.ARK,
};
