export const MOCK_EQUIPMENT = [
	{
		item_equipment_part: "모자",
		item_equipment_slot: "모자",
		item_name: "하이네스 레인져베레",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPCIAHI.png",
		item_description: null,
		item_shape_name: "하이네스 레인져베레",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPCIAHI.png",
		item_gender: null,
		item_total_option: {
			str: "102",
			dex: "242",
			int: "16",
			luk: "0",
			max_hp: "4755",
			max_mp: "360",
			attack_power: "22",
			magic_power: "19",
			armor: "979",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "10",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "40",
			dex: "40",
			int: "0",
			luk: "0",
			max_hp: "360",
			max_mp: "360",
			attack_power: "2",
			magic_power: "0",
			armor: "300",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "10",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 150,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "에픽",
		potential_option_1: "DEX : +9%",
		potential_option_2: "방어력 : +6%",
		potential_option_3: "DEX : +6%",
		additional_potential_option_1: "DEX : +4%",
		additional_potential_option_2: "방어력 : +100",
		additional_potential_option_3: "DEX : +2%",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "56",
			int: "16",
			luk: "0",
			max_hp: "2700",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "12",
		cuttable_count: "7",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "84",
			int: "0",
			luk: "0",
			max_hp: "1440",
			max_mp: "0",
			attack_power: "1",
			magic_power: "0",
			armor: "120",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "62",
			dex: "62",
			int: "0",
			luk: "0",
			max_hp: "255",
			max_mp: "0",
			attack_power: "19",
			magic_power: "19",
			armor: "559",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "상의",
		item_equipment_slot: "상의",
		item_name: "이글아이 레인져후드",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPGJFLH.png",
		item_description: null,
		item_shape_name: "이글아이 레인져후드",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPGJFLH.png",
		item_gender: null,
		item_total_option: {
			str: "112",
			dex: "200",
			int: "0",
			luk: "40",
			max_hp: "1215",
			max_mp: "0",
			attack_power: "22",
			magic_power: "19",
			armor: "503",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "5",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "30",
			dex: "30",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "2",
			magic_power: "0",
			armor: "135",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "5",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 150,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "HP 회복 아이템 및 회복 스킬 효율 : +30%",
		potential_option_2: "DEX : +9%",
		potential_option_3: "DEX : +6%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "이동속도 : +4",
		additional_potential_option_3: "최대 MP : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "20",
			dex: "52",
			int: "0",
			luk: "40",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "8",
		cuttable_count: "8",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "56",
			int: "0",
			luk: "0",
			max_hp: "960",
			max_mp: "0",
			attack_power: "1",
			magic_power: "0",
			armor: "80",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "62",
			dex: "62",
			int: "0",
			luk: "0",
			max_hp: "255",
			max_mp: "0",
			attack_power: "19",
			magic_power: "19",
			armor: "288",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "하의",
		item_equipment_slot: "하의",
		item_name: "트릭스터 레인져팬츠",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPEJGIG.png",
		item_description: null,
		item_shape_name: "트릭스터 레인져팬츠",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPEJGIG.png",
		item_gender: null,
		item_total_option: {
			str: "92",
			dex: "198",
			int: "35",
			luk: "61",
			max_hp: "985",
			max_mp: "0",
			attack_power: "24",
			magic_power: "19",
			armor: "458",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "5",
			all_stat: "6",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "30",
			dex: "30",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "2",
			magic_power: "0",
			armor: "135",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "5",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 150,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "올스탯 : +6%",
		potential_option_2: "DEX : +9%",
		potential_option_3: "최대 MP : +6%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "방어력 : +60",
		additional_potential_option_3: "공격력 : +3",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "64",
			int: "12",
			luk: "36",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "6",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "7",
		cuttable_count: "8",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "1",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "42",
			int: "1",
			luk: "3",
			max_hp: "730",
			max_mp: "0",
			attack_power: "3",
			magic_power: "0",
			armor: "60",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "62",
			dex: "62",
			int: "22",
			luk: "22",
			max_hp: "255",
			max_mp: "0",
			attack_power: "19",
			magic_power: "19",
			armor: "263",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "망토",
		item_equipment_slot: "망토",
		item_name: "아케인셰이드 아처케이프",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOCJOKD.png",
		item_description: null,
		item_shape_name: "아케인셰이드 아처케이프",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOCJOKD.png",
		item_gender: null,
		item_total_option: {
			str: "65",
			dex: "161",
			int: "65",
			luk: "35",
			max_hp: "0",
			max_mp: "0",
			attack_power: "6",
			magic_power: "6",
			armor: "450",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "35",
			dex: "35",
			int: "35",
			luk: "35",
			max_hp: "0",
			max_mp: "0",
			attack_power: "6",
			magic_power: "6",
			armor: "450",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 200,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "방어력 : +3%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "점프력 : +4",
		additional_potential_option_3: "방어력 : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "30",
			dex: "126",
			int: "30",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "7",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "장갑",
		item_equipment_slot: "장갑",
		item_name: "아케인셰이드 아처글러브",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPKJBHG.png",
		item_description: null,
		item_shape_name: "아케인셰이드 아처글러브",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPKJBHG.png",
		item_gender: null,
		item_total_option: {
			str: "68",
			dex: "153",
			int: "0",
			luk: "30",
			max_hp: "0",
			max_mp: "0",
			attack_power: "41",
			magic_power: "0",
			armor: "434",
			speed: "0",
			jump: "5",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "6",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "40",
			dex: "40",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "9",
			magic_power: "0",
			armor: "250",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 200,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "DEX : +3%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "최대 HP : +60",
		additional_potential_option_3: "STR : +6",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "85",
			int: "0",
			luk: "30",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "5",
			boss_damage: "0",
			damage: "0",
			all_stat: "6",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "7",
		cuttable_count: "9",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "1",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "28",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "11",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "28",
			dex: "28",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "4",
			magic_power: "0",
			armor: "184",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "신발",
		item_equipment_slot: "신발",
		item_name: "아케인셰이드 아처슈즈",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPFIGIB.png",
		item_description: null,
		item_shape_name: "아케인셰이드 아처슈즈",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPFIGIB.png",
		item_gender: null,
		item_total_option: {
			str: "131",
			dex: "277",
			int: "0",
			luk: "0",
			max_hp: "1360",
			max_mp: "0",
			attack_power: "27",
			magic_power: "12",
			armor: "818",
			speed: "28",
			jump: "25",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "6",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "40",
			dex: "40",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "9",
			magic_power: "0",
			armor: "250",
			speed: "10",
			jump: "7",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 200,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "올스탯 : +5",
		potential_option_3: "DEX : +3%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "마력 : +3",
		additional_potential_option_3: "최대 MP : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "36",
			dex: "102",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "5",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "6",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "8",
		cuttable_count: "10",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "80",
			int: "0",
			luk: "0",
			max_hp: "1360",
			max_mp: "0",
			attack_power: "1",
			magic_power: "0",
			armor: "120",
			speed: "0",
			jump: "0",
		},
		starforce: "16",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "55",
			dex: "55",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "12",
			magic_power: "12",
			armor: "448",
			speed: "18",
			jump: "18",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "반지",
		item_equipment_slot: "반지1",
		item_name: "글로리온 링 : 슈프림",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEPH.png",
		item_description:
			"연합의 특수팀인 글로리온에서 슈프림 랭크의 팀원에게 지급하는 특별한 반지이다.",
		item_shape_name: "글로리온 링 : 슈프림",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODPEPH.png",
		item_gender: null,
		item_total_option: {
			str: "40",
			dex: "40",
			int: "40",
			luk: "40",
			max_hp: "4000",
			max_mp: "4000",
			attack_power: "25",
			magic_power: "25",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "40",
			dex: "40",
			int: "40",
			luk: "40",
			max_hp: "4000",
			max_mp: "4000",
			attack_power: "25",
			magic_power: "25",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 120,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +9%",
		potential_option_2: "최대 MP : +6%",
		potential_option_3: "최대 HP : +6%",
		additional_potential_option_1: "최대 MP : +100",
		additional_potential_option_2: "INT : +6",
		additional_potential_option_3: "이동속도 : +4",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "반지",
		item_equipment_slot: "반지2",
		item_name: "고귀한 이피아의 반지",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIFGD.png",
		item_description: null,
		item_shape_name: "고귀한 이피아의 반지",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIFGD.png",
		item_gender: null,
		item_total_option: {
			str: "33",
			dex: "39",
			int: "33",
			luk: "33",
			max_hp: "355",
			max_mp: "200",
			attack_power: "2",
			magic_power: "2",
			armor: "12",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "200",
			max_mp: "200",
			attack_power: "2",
			magic_power: "2",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 120,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "LUK : +12",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "공격력 : +3",
		additional_potential_option_3: "최대 HP : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "2",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "6",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "11",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "28",
			dex: "28",
			int: "28",
			luk: "28",
			max_hp: "155",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "12",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "반지",
		item_equipment_slot: "반지3",
		item_name: "여명의 가디언 엔젤 링",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIEPH.png",
		item_description: null,
		item_shape_name: "여명의 가디언 엔젤 링",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIEPH.png",
		item_gender: null,
		item_total_option: {
			str: "75",
			dex: "78",
			int: "79",
			luk: "73",
			max_hp: "555",
			max_mp: "270",
			attack_power: "32",
			magic_power: "28",
			armor: "18",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "200",
			max_mp: "200",
			attack_power: "2",
			magic_power: "2",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 160,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "올스탯 : +6%",
		potential_option_2: "DEX : +6%",
		potential_option_3: "DEX : +6%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "이동속도 : +4",
		additional_potential_option_3: "DEX : +6",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "3",
		cuttable_count: "9",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "4",
			dex: "7",
			int: "8",
			luk: "2",
			max_hp: "100",
			max_mp: "70",
			attack_power: "9",
			magic_power: "5",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "66",
			dex: "66",
			int: "66",
			luk: "66",
			max_hp: "255",
			max_mp: "0",
			attack_power: "21",
			magic_power: "21",
			armor: "18",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "반지",
		item_equipment_slot: "반지4",
		item_name: "마이스터링",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIHLE.png",
		item_description: null,
		item_shape_name: "마이스터링",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEODIHLE.png",
		item_gender: null,
		item_total_option: {
			str: "38",
			dex: "38",
			int: "37",
			luk: "37",
			max_hp: "400",
			max_mp: "230",
			attack_power: "3",
			magic_power: "4",
			armor: "281",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "200",
			max_mp: "200",
			attack_power: "1",
			magic_power: "1",
			armor: "150",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 140,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "4초 당 24의 MP 회복",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "공격력 : +3",
		additional_potential_option_3: "방어력 : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "1",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "2",
			dex: "2",
			int: "1",
			luk: "1",
			max_hp: "20",
			max_mp: "30",
			attack_power: "2",
			magic_power: "3",
			armor: "2",
			speed: "0",
			jump: "0",
		},
		starforce: "12",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "31",
			dex: "31",
			int: "31",
			luk: "31",
			max_hp: "180",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "129",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "펜던트",
		item_equipment_slot: "펜던트",
		item_name: "울프스 퍼플 펜던트",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJHHI.png",
		item_description: null,
		item_shape_name: "울프스 퍼플 펜던트",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJHHI.png",
		item_gender: null,
		item_total_option: {
			str: "31",
			dex: "64",
			int: "39",
			luk: "31",
			max_hp: "360",
			max_mp: "180",
			attack_power: "0",
			magic_power: "0",
			armor: "340",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "2",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "0",
			dex: "16",
			int: "0",
			luk: "0",
			max_hp: "180",
			max_mp: "180",
			attack_power: "0",
			magic_power: "0",
			armor: "185",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 130,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +6%",
		potential_option_3: "최대 HP : +3%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "마력 : +3",
		additional_potential_option_3: "방어력 : +60",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "8",
			int: "8",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "2",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "3",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "9",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "12",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "31",
			dex: "31",
			int: "31",
			luk: "31",
			max_hp: "180",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "155",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "펜던트",
		item_equipment_slot: "펜던트2",
		item_name: "매커네이터 펜던트",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJFLF.png",
		item_description: null,
		item_shape_name: "매커네이터 펜던트",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOAJFLF.png",
		item_gender: null,
		item_total_option: {
			str: "76",
			dex: "87",
			int: "57",
			luk: "65",
			max_hp: "430",
			max_mp: "250",
			attack_power: "1",
			magic_power: "1",
			armor: "188",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "250",
			max_mp: "250",
			attack_power: "1",
			magic_power: "1",
			armor: "100",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 120,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "에픽",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +12",
		potential_option_3: "DEX : +3%",
		additional_potential_option_1: "공격력 : +11",
		additional_potential_option_2: "마력 : +10",
		additional_potential_option_3: "공격력 : +10",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "35",
			dex: "40",
			int: "16",
			luk: "24",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "2",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "6",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "12",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "31",
			dex: "31",
			int: "31",
			luk: "31",
			max_hp: "180",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "88",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "얼굴장식",
		item_equipment_slot: "얼굴장식",
		item_name: "트와일라이트 마크",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPDJALG.png",
		item_description: null,
		item_shape_name: "트와일라이트 마크",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPDJALG.png",
		item_gender: null,
		item_total_option: {
			str: "63",
			dex: "103",
			int: "83",
			luk: "83",
			max_hp: "0",
			max_mp: "0",
			attack_power: "32",
			magic_power: "22",
			armor: "242",
			speed: "0",
			jump: "5",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "7",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "0",
			max_mp: "0",
			attack_power: "5",
			magic_power: "5",
			armor: "100",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 140,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "올스탯 : +6%",
		potential_option_2: "INT : +6%",
		potential_option_3: "최대 MP : +6%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "공격력 : +3",
		additional_potential_option_3: "마력 : +3",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "40",
			int: "20",
			luk: "20",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "5",
			boss_damage: "0",
			damage: "0",
			all_stat: "7",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "4",
		cuttable_count: "9",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "10",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "58",
			dex: "58",
			int: "58",
			luk: "58",
			max_hp: "0",
			max_mp: "0",
			attack_power: "17",
			magic_power: "17",
			armor: "142",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "눈장식",
		item_equipment_slot: "눈장식",
		item_name: "파풀라투스 마크",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPAJFJG.png",
		item_description: null,
		item_shape_name: "파풀라투스 마크",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPAJFJG.png",
		item_gender: null,
		item_total_option: {
			str: "72",
			dex: "124",
			int: "95",
			luk: "78",
			max_hp: "0",
			max_mp: "0",
			attack_power: "38",
			magic_power: "27",
			armor: "376",
			speed: "0",
			jump: "3",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "4",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "8",
			dex: "8",
			int: "8",
			luk: "8",
			max_hp: "0",
			max_mp: "0",
			attack_power: "1",
			magic_power: "1",
			armor: "150",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 145,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +9%",
		potential_option_2: "LUK : +6%",
		potential_option_3: "DEX : +9%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "DEX : +6",
		additional_potential_option_3: "이동속도 : +4",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "52",
			int: "20",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "6",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "4",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "6",
		cuttable_count: "7",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "6",
			dex: "6",
			int: "9",
			luk: "12",
			max_hp: "0",
			max_mp: "0",
			attack_power: "14",
			magic_power: "9",
			armor: "9",
			speed: "0",
			jump: "3",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "58",
			dex: "58",
			int: "58",
			luk: "58",
			max_hp: "0",
			max_mp: "0",
			attack_power: "17",
			magic_power: "17",
			armor: "217",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "귀고리",
		item_equipment_slot: "귀고리",
		item_name: "데아 시두스 이어링",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPBJFKA.png",
		item_description: null,
		item_shape_name: "데아 시두스 이어링",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEPBJFKA.png",
		item_gender: null,
		item_total_option: {
			str: "86",
			dex: "132",
			int: "66",
			luk: "66",
			max_hp: "0",
			max_mp: "0",
			attack_power: "26",
			magic_power: "30",
			armor: "134",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "0",
			max_mp: "0",
			attack_power: "2",
			magic_power: "2",
			armor: "50",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 130,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "최대 HP : +3%",
		potential_option_3: "DEX : +6%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "최대 MP : +60",
		additional_potential_option_3: "공격력 : +3",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "20",
			dex: "48",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "4",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "6",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "18",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "18",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "61",
			dex: "61",
			int: "61",
			luk: "61",
			max_hp: "0",
			max_mp: "0",
			attack_power: "24",
			magic_power: "24",
			armor: "84",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "어깨장식",
		item_equipment_slot: "어깨장식",
		item_name: "아케인셰이드 아처숄더",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOHJGHJ.png",
		item_description: null,
		item_shape_name: "아케인셰이드 아처숄더",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOHJGHJ.png",
		item_gender: null,
		item_total_option: {
			str: "63",
			dex: "62",
			int: "39",
			luk: "42",
			max_hp: "130",
			max_mp: "0",
			attack_power: "26",
			magic_power: "22",
			armor: "502",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "35",
			dex: "35",
			int: "35",
			luk: "35",
			max_hp: "0",
			max_mp: "0",
			attack_power: "20",
			magic_power: "20",
			armor: "300",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 200,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "에픽",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "STR : +3%",
		additional_potential_option_1: "최대 MP : +5%",
		additional_potential_option_2: "DEX : +2%",
		additional_potential_option_3: "공격력 : +10",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "2",
		cuttable_count: "255",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "3",
			dex: "2",
			int: "4",
			luk: "7",
			max_hp: "0",
			max_mp: "0",
			attack_power: "6",
			magic_power: "2",
			armor: "5",
			speed: "0",
			jump: "0",
		},
		starforce: "10",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "25",
			dex: "25",
			int: "0",
			luk: "0",
			max_hp: "130",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "197",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "뱃지",
		item_equipment_slot: "뱃지",
		item_name: "크리스탈 웬투스 뱃지",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOKJHGG.png",
		item_description: null,
		item_shape_name: "크리스탈 웬투스 뱃지",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOKJHGG.png",
		item_gender: null,
		item_total_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "5",
			magic_power: "5",
			armor: "0",
			speed: "10",
			jump: "10",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "5",
			magic_power: "5",
			armor: "0",
			speed: "10",
			jump: "10",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 130,
		},
		potential_option_grade: null,
		additional_potential_option_grade: null,
		potential_option_1: null,
		potential_option_2: null,
		potential_option_3: null,
		additional_potential_option_1: null,
		additional_potential_option_2: null,
		additional_potential_option_3: null,
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "벨트",
		item_equipment_slot: "벨트",
		item_name: "골든 클로버 벨트",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOBJFJD.png",
		item_description: null,
		item_shape_name: "골든 클로버 벨트",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOBJFJD.png",
		item_gender: null,
		item_total_option: {
			str: "46",
			dex: "119",
			int: "70",
			luk: "46",
			max_hp: "330",
			max_mp: "150",
			attack_power: "1",
			magic_power: "1",
			armor: "277",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "4",
			damage: "0",
			equipment_level_decrease: 25,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "15",
			dex: "15",
			int: "15",
			luk: "15",
			max_hp: "150",
			max_mp: "150",
			attack_power: "1",
			magic_power: "1",
			armor: "150",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 140,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +6%",
		potential_option_2: "DEX : +3%",
		potential_option_3: "최대 MP : +3%",
		additional_potential_option_1: "공격력 : +10",
		additional_potential_option_2: "마력 : +3",
		additional_potential_option_3: "공격력 : +3",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "64",
			int: "24",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "4",
			equipment_level_decrease: 25,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "3",
		cuttable_count: "10",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "9",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "12",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "31",
			dex: "31",
			int: "31",
			luk: "31",
			max_hp: "180",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "127",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "훈장",
		item_equipment_slot: "훈장",
		item_name: "우르스 격파왕",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOGJPJI.png",
		item_description: "우르스를 10회 클리어 하면 획득할 수 있는 훈장이다.",
		item_shape_name: "우르스 격파왕",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOGJPJI.png",
		item_gender: null,
		item_total_option: {
			str: "7",
			dex: "7",
			int: "7",
			luk: "7",
			max_hp: "0",
			max_mp: "0",
			attack_power: "7",
			magic_power: "7",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "7",
			dex: "7",
			int: "7",
			luk: "7",
			max_hp: "0",
			max_mp: "0",
			attack_power: "7",
			magic_power: "7",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 100,
		},
		potential_option_grade: null,
		additional_potential_option_grade: null,
		potential_option_1: null,
		potential_option_2: null,
		potential_option_3: null,
		additional_potential_option_1: null,
		additional_potential_option_2: null,
		additional_potential_option_3: null,
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "활",
		item_equipment_slot: "무기",
		item_name: "아케인셰이드 보우",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KELHJFLG.png",
		item_description: null,
		item_shape_name: "아케인셰이드 보우",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KELHJFLG.png",
		item_gender: null,
		item_total_option: {
			str: "170",
			dex: "206",
			int: "0",
			luk: "0",
			max_hp: "255",
			max_mp: "255",
			attack_power: "686",
			magic_power: "73",
			armor: "0",
			speed: "19",
			jump: "0",
			boss_damage: "30",
			ignore_monster_armor: "20",
			all_stat: "0",
			damage: "6",
			equipment_level_decrease: 25,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "100",
			dex: "100",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "276",
			magic_power: "0",
			armor: "0",
			speed: "19",
			jump: "0",
			boss_damage: "30",
			ignore_monster_armor: "20",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 200,
		},
		potential_option_grade: "레전드리",
		additional_potential_option_grade: "에픽",
		potential_option_1: "공격력 : +12%",
		potential_option_2: "데미지 : +9%",
		potential_option_3: "공격력 : +9%",
		additional_potential_option_1: "공격력 : +6%",
		additional_potential_option_2: "크리티컬 확률 : +4%",
		additional_potential_option_3: "STR : +12",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "170",
			magic_power: "73",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "6",
			all_stat: "0",
			equipment_level_decrease: 25,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "9",
		cuttable_count: "8",
		golden_hammer_flag: "적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: "위대한 블러디퀸의 소울 적용",
		soul_option: "올스탯 : +5%",
		item_etc_option: {
			str: "0",
			dex: "36",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "81",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "17",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "70",
			dex: "70",
			int: "0",
			luk: "0",
			max_hp: "255",
			max_mp: "255",
			attack_power: "159",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "보석",
		item_equipment_slot: "보조무기",
		item_name: "에레브의 광휘",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEMHJOJD.png",
		item_description: null,
		item_shape_name: "에레브의 광휘",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEMHJOJD.png",
		item_gender: null,
		item_total_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "3",
			magic_power: "3",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "3",
			magic_power: "3",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 100,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "에픽",
		potential_option_1: "공격력 : +9%",
		potential_option_2: "공격력 : +6%",
		potential_option_3: "크리티컬 확률 : +8%",
		additional_potential_option_1: "공격력 : +6%",
		additional_potential_option_2: "데미지 : +3%",
		additional_potential_option_3: "DEX : +3%",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "엠블렘",
		item_equipment_slot: "엠블렘",
		item_name: "골드 시그너스 엠블렘",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOLLPOA.png",
		item_description: null,
		item_shape_name: "골드 시그너스 엠블렘",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOLLPOA.png",
		item_gender: null,
		item_total_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "2",
			magic_power: "2",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "2",
			magic_power: "2",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 100,
		},
		potential_option_grade: "유니크",
		additional_potential_option_grade: "레전드리",
		potential_option_1: "올스탯 : +6%",
		potential_option_2: "공격력 : +6%",
		potential_option_3: "몬스터 방어율 무시 : +15%",
		additional_potential_option_1: "최대 MP : +11%",
		additional_potential_option_2: "최대 MP : +8%",
		additional_potential_option_3: "마력 : +9%",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "포켓 아이템",
		item_equipment_slot: "포켓 아이템",
		item_name: "핑크빛 성배",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOEJHME.png",
		item_description: null,
		item_shape_name: "핑크빛 성배",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEOEJHME.png",
		item_gender: null,
		item_total_option: {
			str: "5",
			dex: "45",
			int: "5",
			luk: "5",
			max_hp: "50",
			max_mp: "50",
			attack_power: "11",
			magic_power: "5",
			armor: "0",
			speed: "0",
			jump: "3",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "5",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "5",
			dex: "5",
			int: "5",
			luk: "5",
			max_hp: "50",
			max_mp: "50",
			attack_power: "5",
			magic_power: "5",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 140,
		},
		potential_option_grade: null,
		additional_potential_option_grade: null,
		potential_option_1: null,
		potential_option_2: null,
		potential_option_3: null,
		additional_potential_option_1: null,
		additional_potential_option_2: null,
		additional_potential_option_3: null,
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "40",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "6",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "3",
			boss_damage: "0",
			damage: "0",
			all_stat: "5",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "0",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "0",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
	{
		item_equipment_part: "기계 심장",
		item_equipment_slot: "기계 심장",
		item_name: "리튬 하트",
		item_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEJFJHMB.png",
		item_description: null,
		item_shape_name: "리튬 하트",
		item_shape_icon:
			"https://open.api.nexon.com/static/maplestory/ItemIcon/KEJFJHMB.png",
		item_gender: null,
		item_total_option: {
			str: "13",
			dex: "13",
			int: "13",
			luk: "13",
			max_hp: "50",
			max_mp: "0",
			attack_power: "14",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			damage: "0",
			equipment_level_decrease: 0,
			max_hp_rate: "0",
			max_mp_rate: "0",
		},
		item_base_option: {
			str: "3",
			dex: "3",
			int: "3",
			luk: "3",
			max_hp: "50",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			ignore_monster_armor: "0",
			all_stat: "0",
			max_hp_rate: "0",
			max_mp_rate: "0",
			base_equipment_level: 30,
		},
		potential_option_grade: "에픽",
		additional_potential_option_grade: "레어",
		potential_option_1: "DEX : +2%",
		potential_option_2: "DEX : +4",
		potential_option_3: "DEX : +1%",
		additional_potential_option_1: "DEX : +1%",
		additional_potential_option_2: "INT : +2",
		additional_potential_option_3: "최대 HP : +15",
		equipment_level_increase: 0,
		item_exceptional_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
		},
		item_add_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
			boss_damage: "0",
			damage: "0",
			all_stat: "0",
			equipment_level_decrease: 0,
		},
		growth_exp: 0,
		growth_level: 0,
		scroll_upgrade: "7",
		cuttable_count: "255",
		golden_hammer_flag: "미적용",
		scroll_resilience_count: "0",
		scroll_upgradeable_count: "0",
		soul_name: null,
		soul_option: null,
		item_etc_option: {
			str: "0",
			dex: "0",
			int: "0",
			luk: "0",
			max_hp: "0",
			max_mp: "0",
			attack_power: "14",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		starforce: "5",
		starforce_scroll_flag: "미사용",
		item_starforce_option: {
			str: "10",
			dex: "10",
			int: "10",
			luk: "10",
			max_hp: "0",
			max_mp: "0",
			attack_power: "0",
			magic_power: "0",
			armor: "0",
			speed: "0",
			jump: "0",
		},
		special_ring_level: 0,
		date_expire: null,
	},
];
